config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :searches
  root "searches#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/search_validator.rb
class SearchValidator < ActiveModel::Validator 
    def validate(record)
        scanner = SkyScanner.new
        result = scanner.find_airports(record.package_data)
        # This is the response generated by the SkyScanner API when invalid parameters (or no parameters) are passed in
        record.errors.add(:base, "data not found via API") if result.code == "404" || result.code == "400"
    end
end

app/models/search.rb
class Search < ApplicationRecord
    validates :query, presence: true
    validates :country, presence: true
    validates :currency, presence: true
    validates :locale, presence: true
    validates_with SearchValidator

    def package_data
        result = {}
        result["query"] = self.query
        result["country"] = self.country
        result["currency"] = self.currency
        result["locale"] = self.locale
        result
    end

    def airports
        JSON.parse(skyscanner.find_airports(package_data).body)
    end

    def skyscanner
        SkyScanner.new
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def show
        @search = Search.find(params[:id])
        @airports = @search.airports["Places"]
    end

    def new
        @search = Search.new
    end

    def create
        @search = Search.new(search_params)
        respond_to do |format|
            if @search.save
                format.html { redirect_to @search }
            else
                format.html { render :new }
            end
        end
    end

    private

    def search_params
        params.require(:search).permit(:query, :country, :currency, :locale)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flightfinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark mb-5" role="navigation">
        <div class="navbar-brand">
            <%= link_to("Home", new_search_url, class: "navbar-item") %>
        </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<div class="columns has-text-centered">
    <div class="column"></div>
    <div class="column">
        <div class="box">
            <h2 class="title is-2">Find Airports in Your City</h2>
            <%= form_for @search do |f| %>
                <%= f.text_field :query, class: "input is-fullwidth mb-4", placeholder: "Enter City" %>
                <%= f.hidden_field :locale, :value => "en-US" %>
                <%= f.hidden_field :country, :value => "US" %>
                <%= f.hidden_field :currency, :value => "USD" %>
                <%= f.submit class: "button is-fullwidth is-success" %>
            <% end %>
        </div>
    </div>
    <div class="column"></div>
</div>

app/views/searches/show.html.erb
<div class="columns has-text-centered">
    <div class="column"></div>
    <div class="column">
        <h2 class="title is-2">Results</h2>
        <% @airports.each do |airport| %>
            <div class="box">

                <div class="columns has-text-centered">
                    <div class="column">
                        <h2 class="title is-6">Airport</h2>
                        <p><%= airport["PlaceName"] %></p>
                    </div>
                    <div class="column">
                        <h2 class="title is-6">Country</h2>
                        <p><%= airport["CountryName"] %></p>
                    </div>
                </div>

            </div>
        <% end %>
    </div>
    <div class="column"></div>
</div>